[versions]
# --- Android / Kotlin ---
agp = "8.13.1"
kotlin = "2.2.21"
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
material3-icons = "1.7.8"

# --- Compose ---
composeBom = "2025.11.00"
activityCompose = "1.11.0"
lifecycleRuntimeKtx = "2.9.4"

# --- Firebase ---
firebaseBom = "34.6.0"
firebase-crashlytics-gradle = "3.0.6"
google-services = "4.4.4"
firebase-perf-plugin = "2.0.2"

# --- DataStore ---
datastore = "1.1.7"

# --- DI / Hilt ---
hilt = "2.57.2"
hiltNavigationComposeVersion = "1.3.0"


# --- Navigation ---
navigation = "2.9.6"

# --- Coroutines ---
coroutines = "1.10.2"

# --- Serialization ---
serialization = "1.9.0"

# --- Coil (images) ---
coil = "3.3.0"

# --- Testing ---
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
mockk = "1.14.6"
truth = "1.4.5"

# --- KSP ---
ksp = "2.1.20-2.0.1"

# --- OkHttp ---
okHttp3Version = "5.3.0"
playServicesTasks = "18.4.0"

# --- Room ---
roomKtxVersion = "2.8.3"

[libraries]
# --- Android core ---
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# --- Compose ---
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

# Firebase BOM (maneja versiones internas de Firebase)
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
google-service = { module = "com.google.gms:google-services", version.ref = "google-services"}


# Firebase KTX Libraries

firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
firebase-database = { module = "com.google.firebase:firebase-database" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }


# --- Hilt ---
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationComposeVersion" }

# --- DataStore ---
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# --- Kotlin Coroutines ---
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }

# --- Kotlin Serialization ---
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }


# --- Coil---
coil3-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil"}
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

# --- Material 3---
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material3-icons" }

# --- okhttp---

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp3Version" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okHttp3Version" }

# --- Room ---
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtxVersion" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtxVersion" }
room-paging = { module = "androidx.room:room-paging", version.ref = "roomKtxVersion" }


# --- Testing ---
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

gradle = "com.android.tools.build:gradle:8.13.1"
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin"}
dagger-hilt-agp = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt"}
play-services-tasks = { group = "com.google.android.gms", name = "play-services-tasks", version.ref = "playServicesTasks" }



[plugins]
# --- Android ---
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp  = { id = "com.google.devtools.ksp", version.ref = "ksp" }
# --- Hilt ---
dagger-hilt = { id = "dagger.hilt.android.plugin" }
# --- Kotlin Serialization ---
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
# --- Google services & Firebase ---
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebase-perf-plugin" }
